blank_issues_enabled: false
contact_links:
  - name: "DataSanitizer Q&A and Support"
    url: https://github.com/fslef/DataSanitizer/discussions
    about: "For any questions or to share your thoughts about this powershell module, please visit the GitHub discussion channel."
