name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
    paths-ignore:
      - "CHANGELOG.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "CHANGELOG.md"
  workflow_dispatch:

env:
  buildFolderName: "output"
  buildArtifactName: "output"
  testResultFolderName: "testResults"
  defaultBranch: "main"

jobs:
  build:
    name: Build Module
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitVersion (v5.x)
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '5.x'

      - name: Determine version (GitVersion)
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.2.1
        with:
          useConfigFile: false

      - name: Build & Package Module
        run: pwsh ./build.ps1 -ResolveDependency -UseModulefast -Tasks pack
        env:
          ModuleVersion: ${{ steps.gitversion.outputs.NuGetVersionV2 }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: |
            ./build.ps1
            ./build.yaml
            ./RequiredModules/
            ./tests/
            ./output/

  test_linux:
    name: Unit Tests - Linux
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: .

      - name: Run Unit Tests (Linux)
        run: pwsh ./build.ps1 -Tasks test

      - name: Upload Test Results (Linux)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: CodeCoverageLinux
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/

  test_macos:
    name: Unit Tests - macOS
    needs: build
    runs-on: macos-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: .

      - name: Run Unit Tests (macOS)
        run: pwsh ./build.ps1 -Tasks test

      - name: Upload Test Results (macOS)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: CodeCoverageMacOS
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/

  test_windows_ps51:
    name: Unit Tests - Windows PowerShell 5.1
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: .

      - name: Run Unit Tests (Windows PS 5.1)
        run: pwsh ./build.ps1 -Tasks test
        shell: powershell

      - name: Upload Test Results (Windows PS 5.1)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: CodeCoverageWinPS51
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/

  test_windows_ps7:
    name: Unit Tests - Windows PowerShell 7
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: .

      - name: Run Unit Tests (Windows PS 7)
        run: pwsh ./build.ps1 -Tasks test

      - name: Upload Test Results (Windows PS 7)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: CodeCoverageWinPS7
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/

  code_coverage:
    name: Merge & Publish Code Coverage
    needs: [test_linux, test_macos, test_windows_ps51, test_windows_ps7]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: ${{ env.buildFolderName }}

      - name: Download Test Artifact (Linux)
        uses: actions/download-artifact@v4
        with:
          name: CodeCoverageLinux
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}

      - name: Download Test Artifact (macOS)
        uses: actions/download-artifact@v4
        with:
          name: CodeCoverageMacOS
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}

      - name: Download Test Artifact (Windows PS5.1)
        uses: actions/download-artifact@v4
        with:
          name: CodeCoverageWinPS51
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}

      - name: Download Test Artifact (Windows PS7)
        uses: actions/download-artifact@v4
        with:
          name: CodeCoverageWinPS7
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}

      - name: Merge coverage files
        run: pwsh ./build.ps1 -Tasks merge

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/JaCoCo_coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    name: Deploy Module
    needs: [code_coverage]
    runs-on: ubuntu-latest
    if: ${{ (github.event_name != 'pull_request') && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) && success() }}
    steps:

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: ${{ env.buildFolderName }}

      - name: Publish Release
        run: pwsh ./build.ps1 -Tasks publish
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
          GalleryApiToken: ${{ secrets.GALLERY_API_TOKEN }}
          ReleaseBranch: ${{ env.defaultBranch }}
          MainGitBranch: ${{ env.defaultBranch }}

      - name: Create Changelog PR
        run: pwsh ./build.ps1 -Tasks Create_ChangeLog_GitHub_PR
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
          ReleaseBranch: ${{ env.defaultBranch }}
          MainGitBranch: ${{ env.defaultBranch }}
